### ISSUE TITLE
Коннектор к SQLLiteWEB

### ISSUE THREAD

**Issue by asosnoviy** [nixel2007/entity#17]
Поскольку в Оскрипт.WEB своя реализация SQLLite, то и коннектор нужен свой.

**Comment by allustin** [comment]
Она не совсем своя - она как бы базируетcя на ASP.NET DBContext после чего доступен объект `Запрос` - явного коннектора к SQLIte или PG нет. Есть просто поддержка SQlite, MSSQl и PG

https://github.com/EvilBeaver/OneScript.Web/blob/develop/src/OneScript/Database/DbQueryContext.cs#L12

То есть в качестве коннектора может быть представлен только объект "Запрос"

Я так понимаю поэтому нужно #26
