### ISSUE TITLE
При использовании ОС.Веб блокируются запросы после ошибки на уровне SQL (Коннектор SQLite)

### ISSUE THREAD

**Issue by ArchLord42RU** [nixel2007/entity#42]
В коннекторе SQL Lite нет обработки особождения семафора если Запрос.ВыполнитьКоманду() выкидывает исключение:

https://github.com/nixel2007/entity/blob/develop/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80SQLite.os#L175-L189

**Comment by nixel2007** [comment]
Ох ты, и правда. Надо добавить попытку. Пильнешь?

**Comment by ArchLord42RU** [comment]
Пильну)
