### ISSUE TITLE
При падении тестов Action успешно выполняется

### ISSUE THREAD

**Issue by otymko** [nixel2007/entity#52]
Вызвать исключение не меняет код возврата выполнения скрипта:
https://github.com/nixel2007/entity/blob/41d0967c29836b36af20784cd55d0f082363f751/tasks/test.os#L84

В данном случае будет код возврата = 0.

**Comment by nixel2007** [comment]
Странно, вроде на трависе билд падал. Точно ли проблема в вызове исключения здесь? Может проблема в coverage.os?

**Comment by otymko** [comment]
Я к тому, что даже при неудачном прохождении тестов - action будет считаться успешным

**Comment by nixel2007** [comment]
Который из экшенов? Основной или qa?

**Comment by otymko** [comment]
@nixel2007 у тебя не используется опм для запуска тестов. Все должно работать
