### ISSUE TITLE
Расширение типов для колонок

### ISSUE THREAD

**Issue by Absolemus** [nixel2007/entity#71]
Расширить типы для колонки:
1. Тип ```&Колонка(Тип = "Тип")``` - чтобы в поле можно было положить например Тип("Строка")
2. ДвоичныеДанные ```&Колонка(Тип = "ДвоичныеДанные ")```

**Comment by nixel2007** [comment]
Если ДД я ещё могу понять, как смапить на СУБД, то на что должен мапиться Тип?

**Comment by Absolemus** [comment]
Давай вычеркнем пункт 2. В любом случае oscript не умеет приводить значение к типу "тип" и просто выдает пустое значение. Если не против ДД, я могу отправить ПР
![image](https://github.com/nixel2007/entity/assets/20809734/a75a76c2-6e3e-40bf-aa85-4f014092255c)

**Comment by nixel2007** [comment]
Да, конечно, давай
